name: Tag new releases
on:
  push:
    branches:
    - main
    - release-*

jobs:

  tag-release:
    name: Bump tag in ${{ github.ref }}

    runs-on: ubuntu-20.04

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
      with:
        egress-policy: audit

    - name: Check out code
      uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      with:
        fetch-depth: 0
    - name: Bump version and push tag
      id: bump-version
      uses: anothrNick/github-tag-action@43ed073f5c1445ca8b80d920ce2f8fa550ae4e8d
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        TAG_CONTEXT: branch
        RELEASE_BRANCHES: .*
